version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: jobboard_db
      POSTGRES_USER: jobboard_user
      POSTGRES_PASSWORD: changeme
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=jobboard_db
      - POSTGRES_USER=jobboard_user
      - POSTGRES_PASSWORD=changeme
    depends_on:
      - db

volumes:
  pgdata:
